name: Build Launcher

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller --noconsole --name "MinecraftLauncher" --onefile launcher_server.py
      - uses: actions/upload-artifact@v3
        with:
          name: MinecraftLauncher
          path: dist/MinecraftLauncher.exe
