name: Build Launcher

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build launcher exe
        run: pyinstaller --noconsole --name "MinecraftLauncher" --onefile launcher_server.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MinecraftLauncher
          path: dist/MinecraftLauncher.exe
